In [26]:
#zadanie1, metoda Jacobiego
import numpy as np

def jacobi_solve(A: np.matrix, b: np.matrix, ite = 1000) -> np.matrix:
    n = A.shape[0]
    x = np.zeros(n)
    k = 0
    while k < ite:
        x1 = np.zeros(n)
        for i in range(n):
            sum = 0
            for j in range(n):
                if j != i:
                    sum = sum + A[i,j] * x[j]
            x1[i] = (1 / A[i,i]) * (b[i] - sum)
        x = x1
        k = k + 1
    return x

In [27]:
#testowanie
A1 = np.matrix([[2, 1],
               [5, 7]])

b1 = np.matrix([11, 13]).transpose()

jacobi_solve(A1, b1)


array([ 7.11111111, -3.22222222])

In [28]:
#porównanie z metodą eliminacji Gaussa:
#metoda eliminacji Gaussa jest metodą dokładną, a metoda Jacobiego jest metodą iteracyjną

In [29]:
#zadanie2, metoda Gaussa
def gauss_seidel_solve(A: np.matrix, b: np.matrix, ite = 1000) -> np.matrix:
    n = A.shape[0]
    x = np.zeros(n)
    k = 0
    while k < ite:
        x1 = np.zeros(n)
        for i in range(n):
            sum = 0
            for j in range(n):
                if j != i:
                    sum = sum + A[i,j] * x[j]
            x1[i] = (1 / A[i,i]) * (b[i] - sum)
        x = x1
        k = k + 1
    return x

In [30]:
#testowanie
A = np.matrix([[2, 1],
               [5, 7]])
b = np.matrix([11, 13]).transpose()

gauss_seidel_solve(A, b)

array([ 7.11111111, -3.22222222])

In [31]:
#zadanie3, metoda SOR
def sor_solve(A: np.matrix, b: np.matrix, ite = 1000) -> np.matrix:
    n = A.shape[0]
    x = np.zeros(n)
    omega = 1.44
    k = 0
    while k < ite:
        x1 = np.zeros(n)
        for i in range(n):
            sumL = 0
            sumU = 0
            for j in range(0, i):
                sumL = sumL + A[i,j] * x1[j]
            for j in range(i+1, n):
                sumU = sumU + A[i,j] * x[j]
            x1[i] = (1 - omega) * x[i] + (omega / A[i,i]) * (b[i] - sumL - sumU)
        x = x1
        k = k + 1
    return x

In [32]:
#testowanie
A = np.matrix([[2, 1],
               [5, 7]])
b = np.matrix([11, 13]).transpose()

sor_solve(A, b)

array([ 7.11111111, -3.22222222])

In [34]:
#porównanie tempa zbiegania rozwiązania
def check_method(A: np.matrix, b: np.matrix, method):
    xt = np.linalg.solve(A, b)
    for i in range(1,25):
        x = method(A, b, i)
        if(np.allclose(xt.transpose(), x) == True):
            print("Accurate after", i, "iterations")
            break
    pass

A = np.array([[10., -1., 2., 0.],
              [-1., 11., -1., 3.],
              [2., -1., 10., -1.],
              [0.0, 3., -1., 8.]])
b = np.array([6., 25., -11., 15.]).transpose()

check_method(A, b, sor_solve)
check_method(A, b, gauss_seidel_solve)
check_method(A, b, jacobi_solve)


Accurate after 16 iterations
Accurate after 14 iterations
Accurate after 14 iterations
